name: Github actions deploy
on:
  push:
    branches: [main, master, develop. feature/**]
  pull_request:
    branches: [main]

jobs:
  laravel-test-withdb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Laravel Setup
        run: |
          cp .env.testing .env
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
          php artisan key:generate
          php passport install --env=testing
          chmod -R 777 storage bootstrap/cache
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: apiproyecto_test
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: root
        run: |
          php artisan migrate --env=testing
          php aritsan test --filter ProducTest --repeat 50
